### PR TITLE
Remove unneeded run dependencies

### PR DESCRIPTION
**Pull request by xylar**
These libraries should all come in automatically via their run-exports because they were used to build cmor.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@mauzey1, could you please have a look at this and make sure you're okay with the changes?  I don't think this will cause any trouble and it's always better not to have these kinds of over-dependencies.  In particular, we're trying to clean up the usage of `udunits2` at the moment across the conda-forge community.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by mauzey1** [comment]
The only problem I have with this change is that building C or Fortran CMOR programs will require the user to also install udunits2 in their environment.

Python-based programs and PrePARE work fine.

@durack1 @matthew-mizielinski Your thoughts.

**Comment by strandwg** [comment]
> @mauzey1 @xylar I must admit my conda syntax is not up to the challenge of understanding what removing entries from `run:` will do when they are already listed in `requirements:`.
> 
> In the situation that a user wanted to build CMOR themselves using a local compiler, the entire `recipes/` tree would be ignored, right?
> 
> It might be useful to ping a user that compiles, @strandwg, do you have any feedback to provide?

I abandoned getting my Fortran code to compile with CMOR, so I don't have any feedback.

**Comment by xylar** [comment]
> The only problem I have with this change is that building C or Fortran CMOR programs will require the user to also install udunits2 in their environment.

@mauzey1, okay, I wasn't aware that the same package provides a python interface and everything needed for C/Fortran development.  Elsewhere on conda-forge, python packages are nearly always separated from their counterpart C/C++/Fortran libraries, and the latter are divided into just the shared libraries and the full development packages with headers.  We're trying to strip out the development headers from being included as runtime dependencies except where they're needed.  but CMOR seems like a case where they very well may be, in which case I'm fine with just closing this.

**Pull request closed without merging**
